### ISSUE TITLE
Cannot activate 7.17 in Blender 2.90

### ISSUE THREAD

**Issue by jdavies** [mx1001/boxcutter_manual#1]
I just upgraded to BoxCutter 7.17 today. When I try to activate the addon on the Blender preferences dialog (ie I check the checkbox) I get the following error message:

```bpy.ops.transform.resize(value=(2, 1, 1), orient_type='GLOBAL', orient_matrix=((1, 0, 0), (0, 1, 0), (0, 0, 1)), orient_matrix_type='GLOBAL', constraint_axis=(True, False, False), mirror=True, use_proportional_edit=False, proportional_edit_falloff='SMOOTH', proportional_size=1, use_proportional_connected=False, use_proportional_projected=False)
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\jeff\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Boxcutter\__init__.py", line 28, in <module>
    from . import addon
  File "C:\Users\jeff\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Boxcutter\addon\__init__.py", line 1, in <module>
    from . import icon, operator, panel, property, header, keymap, pie, toolbar
  File "C:\Users\jeff\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Boxcutter\addon\operator\__init__.py", line 5, in <module>
    from . import gizmo, property, shape, modifier, popover, tool_activate, web
  File "C:\Users\jeff\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Boxcutter\addon\operator\property\__init__.py", line 5, in <module>
    from . import shape_type
  File "C:\Users\jeff\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Boxcutter\addon\operator\property\shape_type.py", line 7, in <module>
    from .. utility import st3_simple_notification
ImportError: cannot import name 'st3_simple_notification' from 'Boxcutter.addon.operator.utility' (C:\Users\jeff\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Boxcutter\addon\operator\utility\__init__.py)

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\jeff\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Boxcutter\__init__.py", line 28, in <module>
    from . import addon
  File "C:\Users\jeff\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Boxcutter\addon\__init__.py", line 1, in <module>
    from . import icon, operator, panel, property, header, keymap, pie, toolbar
  File "C:\Users\jeff\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Boxcutter\addon\operator\__init__.py", line 5, in <module>
    from . import gizmo, property, shape, modifier, popover, tool_activate, web
  File "C:\Users\jeff\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Boxcutter\addon\operator\property\__init__.py", line 5, in <module>
    from . import shape_type
  File "C:\Users\jeff\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Boxcutter\addon\operator\property\shape_type.py", line 7, in <module>
    from .. utility import st3_simple_notification
ImportError: cannot import name 'st3_simple_notification' from 'Boxcutter.addon.operator.utility' (C:\Users\jeff\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Boxcutter\addon\operator\utility\__init__.py)

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\jeff\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Boxcutter\__init__.py", line 28, in <module>
    from . import addon
  File "C:\Users\jeff\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Boxcutter\addon\__init__.py", line 1, in <module>
    from . import icon, operator, panel, property, header, keymap, pie, toolbar
  File "C:\Users\jeff\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Boxcutter\addon\operator\__init__.py", line 5, in <module>
    from . import gizmo, property, shape, modifier, popover, tool_activate, web
  File "C:\Users\jeff\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Boxcutter\addon\operator\property\__init__.py", line 5, in <module>
    from . import shape_type
  File "C:\Users\jeff\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Boxcutter\addon\operator\property\shape_type.py", line 7, in <module>
    from .. utility import st3_simple_notification
ImportError: cannot import name 'st3_simple_notification' from 'Boxcutter.addon.operator.utility' (C:\Users\jeff\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Boxcutter\addon\operator\utility\__init__.py)

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\jeff\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Boxcutter\__init__.py", line 28, in <module>
    from . import addon
  File "C:\Users\jeff\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Boxcutter\addon\__init__.py", line 1, in <module>
    from . import icon, operator, panel, property, header, keymap, pie, toolbar
  File "C:\Users\jeff\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Boxcutter\addon\operator\__init__.py", line 5, in <module>
    from . import gizmo, property, shape, modifier, popover, tool_activate, web
  File "C:\Users\jeff\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Boxcutter\addon\operator\property\__init__.py", line 5, in <module>
    from . import shape_type
  File "C:\Users\jeff\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Boxcutter\addon\operator\property\shape_type.py", line 7, in <module>
    from .. utility import st3_simple_notification
ImportError: cannot import name 'st3_simple_notification' from 'Boxcutter.addon.operator.utility' (C:\Users\jeff\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Boxcutter\addon\operator\utility\__init__.py)

bpy.context.area.ui_type = 'CONSOLE'
bpy.context.area.ui_type = 'INFO'
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\jeff\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Boxcutter\__init__.py", line 28, in <module>
    from . import addon
  File "C:\Users\jeff\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Boxcutter\addon\__init__.py", line 1, in <module>
    from . import icon, operator, panel, property, header, keymap, pie, toolbar
  File "C:\Users\jeff\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Boxcutter\addon\operator\__init__.py", line 5, in <module>
    from . import gizmo, property, shape, modifier, popover, tool_activate, web
  File "C:\Users\jeff\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Boxcutter\addon\operator\property\__init__.py", line 5, in <module>
    from . import shape_type
  File "C:\Users\jeff\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Boxcutter\addon\operator\property\shape_type.py", line 7, in <module>
    from .. utility import st3_simple_notification
ImportError: cannot import name 'st3_simple_notification' from 'Boxcutter.addon.operator.utility' (C:\Users\jeff\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Boxcutter\addon\operator\utility\__init__.py)```

Any ideas if I'm doing something wrong or if it is a bug? I'm on Windows 10 with up-to-date patches running Blender 2.90. I have attached my system-info.txt file generated by Blender.
[system-info.txt](https://github.com/mx1001/boxcutter_manual/files/5184179/system-info.txt)

**Comment by proxeIO** [comment]
Looks like hardops needs to be updated, should use the proper support channels, either discord or blender artist thread.
